sudo: required

language: go

go:
  - 1.7

script:
  - sudo mkdir -p /etc/hector; sudo cp config.toml /etc/hector
  - sudo mkdir -p /etc/hector/metadata/alltrade; sudo cp metadata/example/alltrade.json /etc/hector/metadata/alltrade/
  - go test -v ./...
