sudo: required

language: go

go:
  - 1.7

script:
  - sudo mkdir -p /etc/hector; sudo cp -R conf-example/* /etc/hector
  - sudo mkdir -p /var/log/hector; sudo touch /var/log/hector/server.log; sudo chmod -R 777 /var/log/hector
  - go test -v ./...
