# This is the configuration of Hector Server
# Location : /etc/hector/config.toml
# DO NOT DELETE THIS FILE

version = "0.0.1"

# Hector Server Config
[hector]
	connectiontype = "tcp"
	version = "0.0.1"
	port = "9001"
	log = "INFO"
	logdirectory = "/var/log/hector"

# Cassandra Config
[cassandra]
	host = ["172.17.0.3"]

# Presto
[presto]
	connectionUrl = "presto://10.138.32.26:8080/cassandra/ais_test_all"
