# This is the configuration of Hector Server
# Location : /etc/hector/config.toml
# DO NOT DELETE THIS FILE

kversion = "0.0.1"

# Hector Server Config
[hector]
	connectionType = "tcp"
	version = "0.0.1"
	host = "127.0.0.1"
	port = "9001"
	log = "INFO"
	logDirectory = "conf-example"
	startServersOfType = ["http"]

# Cassandra Config
[cassandra]
	host = "10.138.32.77"
	port = "9042"

# Presto
[presto]
	connectionURL = "presto://10.138.32.26:8080/cassandra/ais_test_all"
